from flask import Flask, render_template, jsonify
from gevent import monkey; monkey.patch_all()
from gevent.pywsgi import WSGIServer

app = Flask(__name__)


TEMAS = [
  {
    'id':1,
    'Plantel': 'CBTA 205',
    'Parcial' : 'Parcial 1',
    'Docente(s)': 'M.C. Héctor René Becerril Cejudo',
    'UAC': 'Pensamiento Matemático I',
    'Tema':'Información y toma de decisiones',
    'Temática general': 'Estadísticas para la toma de decisiones',
    'Temática específica': 'Los números como respaldo en la toma de decisiones',
    'Semestre': '1°',
    'Grupos': 'A, B y C',
    'Horas docente': '120 mins',
    'Horas independiente': '0 mins',
    'Contenido': 'Conocerás acerca del poder de la matemática y del pensamiento estadístico y probabilístico en diferentes situaciones de la vida.',
    'pg': 'Progresión 1',
    'pg desc': 'Discute la importancia de la toma razonada de decisiones, tanto a nivel personal como colectivo, utilizando ejemplos reales o ficticios y de problemáticas complejas que sean significativas para valorar la recolección de datos, su organización y la aleatoriedad.<br><br>Se busca llevar al estudiantado a que aprecie el poder de la matemática y el pensamiento estadístico y probabilístico. En este punto no se espera que se resuelvan las problemáticas abordadas.',
    'Conocimientos integradores': '',
    'Dimensión': '',
    'Categoría(s)':'<b>C2</b> Procesos de intuición y razonamiento.',
    'Subcategoría(s)':'<b>S1</b> Capacidad para observar y conjeturar. ',
    'Metas de aprendizaje':'<b>M1</b> Observa y obtiene información de una situación o fenómeno para establecer estrategias o formas de visualización que ayuden a entenderlo. ',
    'Aprendizaje de trayectoria':'',
    'Multi 1': 'Lengua y comunicación - Progresión 1',
    'Multi 2': 'Cultura Digital - Progresión 1',
    'Multi 3': '',
    'Evidencia M1': 'Lectura y Cuestionario',
    'Evidencia M2': 'Correo con archivo adjunto',
    'Evidencia M3': '',
    'Inter 1': '',
    'Inter 2': '',
    'Inter 3': '',
    'Evidencia I1': '',
    'Evidencia I2': '',
    'Evidencia I3': '',
    'Apertura': 'Al inicio de la primera clase se presentan (y se explican con detalle) los criterios de evaluación para el Primer Parcial. Se describirán además los materiales básicos que se utilizarán durante el curso así como algunas herramientas en las que se podrán apoyar como lo es el caso de esta aplicación web y otros sitios como <a href="https://rdrr.io/snippets/" target="_blank">rdrr</a>.<br><br><p style="font-weight:bold;">Lectura grupal</p>. <b>"Sembrar certeza en tierras inciertas"</b><div class="text-center">1</div> En lo más recóndito de un frondoso valle, una pequeña comunidad se prepara para sembrar sus cultivos. Cada año, deben decidir cuánta semilla plantar, en qué terreno y cuándo iniciar la siembra. Decisiones que determinarán la cosecha —y la supervivencia— de todos.<br><br><div class="text-center">2</div>Los ancianos del lugar han registrado durante décadas lluvias, plagas, rendimientos de distintas semillas y épocas de plantación. Gracias a esos datos, ahora saben que en terrenos bajos la humedad tarda más en disiparse, y que sembrar al iniciarse la primavera reduce el riesgo de heladas.<br><br><div class="text-center">3</div>Deciden ordenar los datos: comparar los rendimientos según los suelos, correlacionar fechas de lluvia con brotes fuertes y graficar cuándo las plagas fueron más devastadoras. Así convierten información dispersa en conocimiento útil.<br><br><div class="text-center">4</div>Pero no todo está bajo control. Un año, una tormenta inesperada arrasó parte de la cosecha. Otro, una plaga surgió sin precedentes. Reconocen que la aleatoriedad —lo impredecible— también juega un papel. Ante esto, utilizan estrategias como diversificar cultivos o espaciar la siembra en fechas clave, mitigando riesgos y asegurando alguna cosecha aunque algo falle.<br><br><div class="text-center">5</div>Cada familia decide individualmente cuánto sembrar, pero comparten esfuerzos para comprar semillas resistentes o construir invernaderos improvisados. Las decisiones personales, informadas por datos y adaptadas a la incertidumbre, se retroalimentan del conocimiento colectivo: todos se benefician de información más robusta y de la experiencia compartida.<br><br><div class="text-center">6</div>La cosecha, aunque no perfecta cada año, es cada vez más estable. Aprenden que no basta con sentir o adivinar: entender, analizar, y planear con datos —y con humildad ante lo inesperado— permite tomar decisiones más sólidas.<br><br><div class="actividad"><b>Actividad 1</b><br> En una hoja es cribe tus datos (Nombre completo, fecha, semestre, grupo y carrera) y sigue las instrucciones.<br><br>A continuación se presentan diferentes conceptos y en los paréntesis de la derecha escribe el número de párrafo que crees que se relaciona con cada concepto.<br><br>a) Tomar decisiones personales y colectivas ( &emsp; )<br>b) Recolección de datos ( &emsp; )<br>c) Aleatoriedad o situaciones inesperadas ( &emsp; )<br>d) Resultados y reflexión ( &emsp; )<br>e) Organizar información ( &emsp; )<br><br>Entrega a tu profesor la hoja con la actividad realizada.</div>',
    'Apertura tiempo': 'Docente 15 - Independiente: 0',
    'Apertura tiempo total': 60,
    'Apertura técnicas': 'Conversación guiada y preguntas detonantes',
    'Apertura evidencia': '',
    'Apertura eva diag': 'Participación grupal, lluvia de ideas',
    'Apertura eva inst': '',
    'Apertura eva pond': 5,
    'Caso': 'Juan quiere comprar una motocicleta barata pero le preocupa elegir la marca correcta, una que tenga menos probabilidad de fallar o descomponerse pronto.<br><br>¿Qué crees que podría hacer Juan para conseguir su objetivo?<br><br>Lluvia de ideas para anotar en el pintarrón.',
    'Desarrollo': '<b>Situación 1:</b><br><br>Juan quiere comprar una motocicleta y existen 3 diferentes marcas que le interesan: Xioma, Serpux y Ziron. Juan consultó en internet cuántas motocicletas de cada marca han sido llevadas a servicio a la tienda en los últimos tres meses por fallas y mal funcionamiento. Los resultados fueron los siguiente:<br><br><div class="border-bottom row mx-auto text-center"><div class="col-4">Xioma:</div> <div class="col-4">Serpux:</div>  <div class="col-4">Ziron:</div></div><div class="border-bottom row mx-auto text-center"><div class="col-4">1</div> <div class="col-4">0</div>  <div class="col-4">4</div></div><br><br><div class="actividad"><b>Actividad 2</b><br> En hoja con tus datos escribe la <b>Situación 1</b> así como también los datos de la tabla de marcas de motocicletas, después escribe las siguientes preguntas y con tus propias palabras desarrolla la respuesta de cada una.<br><br>1. ¿Cuál marca presentó fallas con menor <b>frecuencia</b>?<br>2. ¿Cuál marca crees que es la que presenta fallas con mayor <b>frecuencia</b>?<br>3. ¿Cuál marca crees que tiene mayor <b>probabilidad</b> de fallar?¿Por qué?<br>4. ¿Cuál marca crees que debería comprar Juán y por qué?<br><br><p class="navtxt"><b>*Frecuencia</b> se refiere al <b>número</b> de veces que un evento se repite.</p><br><br>Antes de entregar tu actividad al profesor toma una foto de la misma y como <b>Tarea 1</b> deberás enviar esa foto de la actividad por medio de correo electrónico utilizando el siguiente botón. <b>*La fecha límite para enviar la Tarea 1 es el viernes 5 de septiembre a las 09:00 PM.</b></div>',
    'Desarrollo tiempo': 'Docente: 30 min - Independiente: 0 min',
    'Desarrollo tiempo total': 30,
    'Desarrollo técnicas': 'Lluvia de ideas y elaboración de un resumen.',
    'Desarrollo evidencia': 'Resumen',
    'Desarrollo eva diag': '',
    'Desarrollo eva inst': 'Lista de cotejo',
    'Desarrollo eva pond': 5,
    'Laboratorio':'<p style="font-weight:bold;">Laboratorio</p> Esta sección se trabajará en el laboratorio de cómputo donde exploraremos el uso del lenguaje de programación "R".<br><br>Después de que Jorge obtuvo información acerca de los casos de marcas de motocicletas reportadas como defectuosas en los últimos tres meses, se dió a la tarea de buscar información en internet acerca de los casos registrados de motocicletas reportadas como defectuosas en los últimos 2 años. En la página de PROFECO encontró un reporte de casos defectuosos sobre las tres marcas que le interesan, la lista es la siguiente:<br><br>"Ziron", "Ziron" , "Ziron, "Serpux", "Ziron", "Ziron", "Ziron", "Xioma", "Xioma", "Ziron", "Xioma", "Serpux", "Ziron", "Xioma", "Xioma", "Ziron", "Xioma", "Ziron", "Ziron", "Ziron", "Ziron", "Ziron", "Ziron", "Ziron", "Ziron", "Ziron", "Ziron", "Xioma", "Ziron", "Xioma", "Ziron", "Ziron", "Xioma", "Xioma", "Ziron", "Xioma", "Ziron", "Ziron" <br><br>Ahora usa un navegador de internet a ingresa al sitio <a href="https://rdrr.io/snippets/" target="_blank">rdrr</a>. Una vez que abras esta liga verás una pantalla como la siguiente:<br><br><img class="mt-3 mb-3" src="https://matematicas-1.onrender.com/static/rrio_interfase1.JPG" style="width:220px;height:auto">',
    'Laboratorio tiempo total': 60,
    'Laboratorio evidencia': '',
    'Laboratorio eva diag': '',
    'Laboratorio eva inst': '',
    'Laboratorio eva pond': 0,
    'Cierre': '<p style="font-weight:bold;">Lectura grupal</p>. <b>"Decisiones que venden: El poder de los datos en gran retail”</b><br><br><div class="text-center">1</div>Es viernes por la tarde en la sede central de Coppel, con decenas de tiendas repartidas por México. La gerenta regional, Claudia, se enfrenta a una decisión crítica: ¿cómo planificar las compras de saldo de invierno sin terminar con mucho inventario sobrante o escasez en tiendas con alta demanda?<br><br><div class="text-center">2</div>Claudia recurre al sistema de analítica avanzada que integra datos de ventas en tiempo real, patrones de compras pasadas, estacionalidad y días festivos. Utiliza herramientas de inventory optimization y forecasting predictivo, que ayudan a evitar carencias o excesos de producto. Gracias a esto, se ha logrado reducir hasta un 30 % el exceso de inventario, con ahorros visibles en costos y mejor flujo de caja.<br><br><div class="text-center">3</div>Para anticiparse a las necesidades, se aplican modelos estadísticos y de machine learning que predicen demanda según regiones, temporadas y promociones. Estos modelos también permiten ajustar precios dinámicamente, balanceando márgenes y competitividad<br><br><div class="text-center">4</div>El sistema no espera decisiones manuales: usa inteligencia artificial para detectar productos que están por expirar o quedarse sin stock, generando alertas automáticas y recomendaciones de promociones o redistribución de inventario entre sucursales.<br><br><div class="text-center">5</div>Durante una reunión semanal, Claudia muestra en tiempo real un dashboard que revela:<ul><li>Productos más vendidos por tienda.</li><li>Eficiencia del equipo de ventas según conversión y tiempos de atención.</li><li>Necesidades de reposición o promociones locales.</li></ul>Con esta información, las decisiones dejan de depender de corazonadas y se sustenta todo en evidencia cuantitativa.<br><br><div class="text-center">6</div>Gracias a estas medidas:<ul><li>Las ventas crecen en tiendas con alta rotación, al tener productos adecuados en el momento correcto.</li><li>El inventario se reduce en tiendas con baja demanda, evitando pérdidas innecesarias.</li><li>Se promueve una cultura de decisiones fundamentadas en datos y análisis, y no en intuiciones.</li></ul><br><div class="text-center">7</div>En una gran tienda como Coppel, el uso estratégico de matemáticas, tecnología e información convierte decisiones complejas en acciones efectivas, beneficiando tanto lo personal (el trabajo de Claudia) como el éxito colectivo del negocio.<br><br>En tus notas escribe las siguientes preguntas y responde con tus propias palabras con base en la lectura anterior.<br<<br><ul><li>¿Cómo se llama el personaje principal y en que consiste el trabajo que realiza?</li><li>¿Cuál era la situación que le preocupaba al personaje principal?</li><li>¿Qué consideras que fue la clave para que el personaje principal saliera con éxito de la situación?</li><li>¿Cuáles fueron las herramientas o conocimientos principales que le ayudaron al personaje a solucionar la situación?</li></ul><br><br>',
    'Cierre tiempo': 'Docente 15 - Independiente 0',
    'Cierre tiempo total': 30,
    'Cierre técnicas': 'Resumen y uso de las TICCAD',
    'Cierre evidencia': 'Correo electrónico y resumen',
    'Cierre eva diag': '',
    'Cierre eva inst': 'Lista de cotejo',
    'Cierre eva pond': 5,
    'Materiales': '',
    'Equipo': 'Computadora o dispositivo móbil',
    'Fuentes': '',
    'Elaboró':'M.C. Héctor René Becerril Cejudo',
    'Revisó': 'Ing. Ana Lucía Gallegos Castro',
    'Avaló': 'Ing. José Luis Alcalá López',
    'Ponderación pg': 15,
    'src1':'https://matematicas-1.onrender.com/static/pic01 motorcycle.jpg',
    'Ejercicios': 'Con lo que hemos aprendido anteriormente, ahora buscaremos dar solución a algunas situaciones.',
    'Resuelve': 'Para resolver este problema primero ...',
    'Retroalimentación': 'Con la finalidad de tener retroalimentación acerca de los temas anteriormente cubiertos, realizaremos una actividad final antes de continuar con el programa.'
  },
  
  {
    'id':2,
    'Plantel': 'CBTA 205',
    'Parcial' : 'Parcial 1',
    'Docente(s)': 'M.C. Héctor René Becerril Cejudo',
    'UAC': 'Pensamiento Matemático I',
    'Tema':'Variabilidad e Incertidumbre',
    'Temática general': 'Nociones de probabilidad',
    'Temática específica': 'Variabilidad e Incertidumbre',
    'Semestre': '1°',
    'Grupos': 'A, B y C',
    'Horas docente': '60 mins',
    'Horas independiente': '60 mins',
    'Contenido': 'Descubrirás que los resultados de un evento o de un experimento pueden variar cuando este se realiza en repetidas ocasiones.',
    'pg': 'Progresión 2',
    'pg desc': 'Identifica la incertidumbre como consecuencia de la variabilidad y a través de simulaciones considera la frecuencia con la que un evento aleatorio puede ocurrir con la finalidad de tener más información sobre la probabilidad de que dicho evento suceda. ',
    'Conocimientos integradores': '',
    'Dimensión': '',
    'Categoría(s)':'<b>C2</b> Procesos de intuición y razonamiento.',
    'Subcategoría(s)':'<b>S1</b> Capacidad para observar y conjeturar.<br><b>S2</b> Pensamiento intuitivo.',
    'Metas de aprendizaje':'<b>M1</b> Observa y obtiene información de una situación o fenómeno para establecer estrategias o formas de visualización que ayuden a        entenderlo.<br><b>M2</b>   Desarrolla la percepción y la intuición para              generar conjeturas ante situaciones que requieren interpretación',
    'Aprendizaje de trayectoria':'',
    'Multi 1': 'Cultura Digital - Progresión 2',
    'Multi 2': 'Cultura Digital - Progresión 3',
    'Multi 3': 'Cultura Digital - Progresión 5',
    'Evidencia M1': '',
    'Evidencia M2': '',
    'Evidencia M3': '',
    'Inter 1': 'Lengua y Comunicación - Progresión 1 - Semana 2',
    'Inter 2': 'Lengua y Comunicación - Progresión 4 - Semana 3',
    'Inter 3': 'Lengua y Comunicación - Progresión 5 - Semana 4',
    'Evidencia I1': '',
    'Evidencia I2': '',
    'Evidencia I3': '',
    'Apertura': '',
    'Apertura tiempo': '',
    'Apertura tiempo total': 15,
    'Apertura técnicas': '',
    'Apertura evidencia': '',
    'Apertura eva diag': '',
    'Apertura eva inst': '',
    'Apertura eva pond': 0,
    'Caso': 'Se sembraron 15 semillas de jitomate y en una bitácora se registraron datos de sus etapas de desarrollo como:<br> <ul><li>a) días trascurridos desde la siembra hasta la germinación</li><li>b) días transcurridos desde la siembra hasta la aparición de las primeras hoja verdaderas</li><li> c) número de hojas después de 30 días de la germinación</li><li>d) número de hojas después de 45 días de la germinación.</li></ul>',
    'Desarrollo': '',
    'Desarrollo tiempo': '',
    'Desarrollo tiempo total': 30,
    'Desarrollo técnicas': '',
    'Desarrollo evidencia': '',
    'Desarrollo eva diag': '',
    'Desarrollo eva inst': '',
    'Desarrollo eva pond': 10,
    'Laboratorio':'',
    'Laboratorio tiempo total': 0,
    'Laboratorio evidencia': '',
    'Laboratorio eva diag': '',
    'Laboratorio eva inst': '',
    'Laboratorio eva pond': 0,
    'Cierre': '',
    'Cierre tiempo': '',
    'Cierre tiempo total': 15,
    'Cierre técnicas': '',
    'Cierre evidencia': '',
    'Cierre eva diag': '',
    'Cierre eva inst': '',
    'Cierre eva pond': 15,
    'Materiales': '',
    'Equipo': '',
    'Fuentes': '',
    'Elaboró':'',
    'Revisó': '',
    'Avaló': '',
    'Ponderación pg': 30,
'src1':'https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExOHVoZjZtczZwbXJqbms4YmNvZ2lidjk2cDBjcmxqZzloNmR1bnc0eSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/JIX9t2j0ZTN9S/giphy.gif',
    'Ejercicios': 'Con las técnicas y las herramientas que ya vimos anteriormente, ahora buscaremos resolver situaciones diferentes.',
    'Resuelve': 'Para resolver este problema ...',
    'Retroalimentación': 'Con la finalidad de tener retroalimentación acerca de los temas anteriormente cubiertos, realizaremos una actividad final antes de continuar con el programa.'
  },
  
  {
    'id':3,
    'Plantel': 'CBTA 205',
    'Parcial' : 'Parcial 1',
    'Docente(s)': 'M.C. Héctor René Becerril Cejudo',
    'UAC': 'Pensamiento Matemático I',
    'Tema':'Frecuencia y probabilidad',
    'Temática general': 'Fecuencia y probabilidad',
    'Temática específica': 'Frecuencia y probabilidad',
    'Semestre': '1°',
    'Grupos': 'A, B y C',
    'Horas docente': '60 mins',
    'Horas independiente': '60 mins',
    'Contenido': 'Experimentos y pruebas de hipótesis.',
    'pg': 'Progresión 3',
    'pg desc': 'Identifica la equiprobabilidad como una hipótesis que, en caso de que se pueda asumir, facilita el estudio de la probabilidad y observa que cuando se incrementa el número de repeticiones de una simulación, la frecuencia del evento estudiado tiende a su probabilidad teórica.',
    'Conocimientos integradores': '',
    'Dimensión': '',
    'Categoría(s)':'',
    'Subcategoría(s)':'',
    'Metas de aprendizaje':'',
    'Aprendizaje de trayectoria':'',
    'Multi 1': 'Cultura Digital - Progresión 2',
    'Multi 2': 'Cultura Digital - Progresión 3',
    'Multi 3': 'Cultura Digital - Progresión 5',
    'Evidencia M1': '',
    'Evidencia M2': '',
    'Evidencia M3': '',
    'Inter 1': 'Lengua y Comunicación - Progresión 1 - Semana 2',
    'Inter 2': 'Lengua y Comunicación - Progresión 4 - Semana 3',
    'Inter 3': 'Lengua y Comunicación - Progresión 5 - Semana 4',
    'Evidencia I1': '',
    'Evidencia I2': '',
    'Evidencia I3': '',
    'Apertura': '',
    'Apertura tiempo': '',
    'Apertura tiempo total': 10,
    'Apertura técnicas': '',
    'Apertura evidencia': '',
    'Apertura eva diag': '',
    'Apertura eva inst': '',
    'Apertura eva pond': 0,
    'Caso': '¿Recuerdas la lectura acerca de ...',
    'Desarrollo': '',
    'Desarrollo tiempo': '',
    'Desarrollo tiempo total': 30,
    'Desarrollo técnicas': '',
    'Desarrollo evidencia': '',
    'Desarrollo eva diag': '',
    'Desarrollo eva inst': '',
    'Desarrollo eva pond': 15,
    'Laboratorio':'',
    'Laboratorio tiempo total': 60,
    'Laboratorio evidencia': '',
    'Laboratorio eva diag': '',
    'Laboratorio eva inst': '',
    'Laboratorio eva pond': 0,
    'Cierre': '',
    'Cierre tiempo': '',
    'Cierre tiempo total': 20,
    'Cierre técnicas': '',
    'Cierre evidencia': '',
    'Cierre eva diag': '',
    'Cierre eva inst': '',
    'Cierre eva pond': 15,
    'Materiales': '',
    'Equipo': '',
    'Fuentes': '',
    'Elaboró':'',
    'Revisó': '',
    'Avaló': '',
    'Ponderación pg': 30,         'src1':'https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExeW5xNmwzMnhxMWkwZmRwYWU4c2xydzFwYnB2ZWp6ems1NzkyZjh0cCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/BemKqR9RDK4V2/giphy.gif',
    'Ejercicios': 'Con las técnicas y las herramientas que ya vimos anteriormente, ahora buscaremos resolver situaciones diferentes.',
    'Resuelve': 'Con ayuda de tu ptofesor en clase...',
    'Retroalimentación': 'Con la finalidad de tener retroalimentación acerca de los temas anteriormente cubiertos, realizaremos una actividad final antes de continuar con el programa.'
  },
  {
    'id':4,
    'Plantel': 'CBTA 205',
    'Parcial' : 'Parcial 1',
    'Docente(s)': 'M.C. Héctor René Becerril Cejudo',
    'UAC': 'Pensamiento Matemático I',
    'Tema':'Técnicas de conteo',
    'Temática general': 'Técnicas de conteo',
    'Temática específica': 'Técnicas de conteo',
    'Semestre': '1°',
    'Grupos': 'A, B y C',
    'Horas docente': '60 mins',
    'Horas independiente': '60 mins',
    'Contenido': 'Técnicas de conteo.',
    'pg': 'Progresión 4',
    'pg desc': 'Elige una técnica de conteo (ordenaciones con repetición, ordenaciones, permutaciones, combinaciones) para calcular el número total de casos posibles y casos favorables para eventos simples con la finalidad de hallar su probabilidad y con ello generar una mayor conciencia en la toma de decisiones. Las técnicas de conteo se introducen para entender la probabilidad de eventos aleatorios en los que la expresión explícita de su espacio muestral es poco factible.',
    'Conocimientos integradores': '',
    'Dimensión': '',
    'Categoría(s)':'',
    'Subcategoría(s)':'',
    'Metas de aprendizaje':'',
    'Aprendizaje de trayectoria':'',
    'Multi 1': 'Cultura Digital - Progresión 2',
    'Multi 2': 'Cultura Digital - Progresión 3',
    'Multi 3': 'Cultura Digital - Progresión 5',
    'Evidencia M1': '',
    'Evidencia M2': '',
    'Evidencia M3': '',
    'Inter 1': 'Lengua y Comunicación - Progresión 1 - Semana 2',
    'Inter 2': 'Lengua y Comunicación - Progresión 4 - Semana 3',
    'Inter 3': 'Lengua y Comunicación - Progresión 5 - Semana 4',
    'Evidencia I1': '',
    'Evidencia I2': '',
    'Evidencia I3': '',
    'Apertura': '',
    'Apertura tiempo': '',
    'Apertura tiempo total': 20,
    'Apertura técnicas': '',
    'Apertura evidencia': '',
    'Apertura eva diag': '',
    'Apertura eva inst': '',
    'Apertura eva pond': 0,
    'Caso': 'En un grupo de 10 personas, 3 personas son hombres y 7 son mujeres...',
    'Desarrollo': '',
    'Desarrollo tiempo': '',
    'Desarrollo tiempo total': 110,
    'Desarrollo técnicas': '',
    'Desarrollo evidencia': '',
    'Desarrollo eva diag': '',
    'Desarrollo eva inst': '',
    'Desarrollo eva pond': 15,
    'Laboratorio':'',
    'Laboratorio tiempo total': 60,
    'Laboratorio evidencia': '',
    'Laboratorio eva diag': '',
    'Laboratorio eva inst': '',
    'Laboratorio eva pond': 0,
    'Cierre': '',
    'Cierre tiempo': '',
    'Cierre tiempo total': 110,
    'Cierre técnicas': '',
    'Cierre evidencia': '',
    'Cierre eva diag': '',
    'Cierre eva inst': '',
    'Cierre eva pond': 15,
    'Materiales': '',
    'Equipo': '',
    'Fuentes': '',
    'Elaboró':'',
    'Revisó': '',
    'Avaló': '',
    'Ponderación pg': 30,
    'src1':'https://peninsula360press.com/wp-content/uploads/2021/01/wp2297919-1600x1000.jpg',
    'Ejercicios': 'Con las técnicas y las herramientas que ya vimos anteriormente, ahora buscaremos resolver situaciones diferentes.',
    'Resuelve': 'Para resolver este problema primero ...',
    'Retroalimentación': 'Con la finalidad de tener retroalimentación acerca de los temas anteriormente cubiertos, realizaremos una actividad final para entregar antes de continuar con el programa.'
  },
  {
  'id':5,
    'Plantel': 'CBTA 205',
    'Parcial' : 'Parcial 2',
    'Docente(s)': 'M.C. Héctor René Becerril Cejudo',
    'UAC': 'Pensamiento Matemático I',
    'Tema':'Probabilidad condicional',
    'Temática general': 'Probabilidad',
    'Temática específica': 'Probabilidad condicional',
    'Semestre': '1°',
    'Grupos': 'A, B y C',
    'Horas docente': '180 mins',
    'Horas independiente': '60 mins',
    'Contenido': 'Estabilidad frecuencial y probabilidad.',
    'pg': 'Progresión 5',
    'pg desc': 'Observa cómo la probabilidad de un evento puede actualizarse cuando se obtiene más información al respecto y considera eventos excluyentes e independientes para emplearlos en la determinación de probabilidades condicionales. La introducción de la actualización de probabilidades se hace a través de simulaciones y sólo después se aborda el teorema de Bayes.',
    'Conocimientos integradores': '',
    'Dimensión': '',
    'Categoría(s)':'<b>C2</b> Procesos de intuición y razonamiento.',
    'Subcategoría(s)':'<b>S1</b> Capacidad para observar y conjeturar.<br><b>S2</b> Pensamiento intuitivo.<br><b>S3</b> Pensamiento formal.',
    'Metas de aprendizaje':'<b>M4</b> rgumenta a favor o en contra de afirmaciones acerca de situaciones, fenómenos o problemas propios de la matemática, de las ciencias o de su contexto ',
    'Aprendizaje de trayectoria':'',
    'Multi 1': 'Cultura Digital - Progresión 2',
    'Multi 2': 'Cultura Digital - Progresión 3',
    'Multi 3': 'Cultura Digital - Progresión 5',
    'Evidencia M1': '',
    'Evidencia M2': '',
    'Evidencia M3': '',
    'Inter 1': 'Lengua y Comunicación - Progresión 1 - Semana 2',
    'Inter 2': 'Lengua y Comunicación - Progresión 4 - Semana 3',
    'Inter 3': 'Lengua y Comunicación - Progresión 5 - Semana 4',
    'Evidencia I1': '',
    'Evidencia I2': '',
    'Evidencia I3': '',
    'Apertura': '',
    'Apertura tiempo': '',
    'Apertura tiempo total': 30,
    'Apertura técnicas': '',
    'Apertura evidencia': '',
    'Apertura eva diag': '',
    'Apertura eva inst': '',
    'Apertura eva pond': 0,
    'Caso': 'En un grupo de 10 personas, 3 personas son ...',
    'Desarrollo': '',
    'Desarrollo tiempo': '',
    'Desarrollo tiempo total': 120,
    'Desarrollo técnicas': '',
    'Desarrollo evidencia': '',
    'Desarrollo eva diag': '',
    'Desarrollo eva inst': '',
    'Desarrollo eva pond': 5,
    'Laboratorio':'',
    'Laboratorio tiempo total': 60,
    'Laboratorio evidencia': '',
    'Laboratorio eva diag': '',
    'Laboratorio eva inst': '',
    'Laboratorio eva pond': 0,
    'Cierre': '',
    'Cierre tiempo': '',
    'Cierre tiempo total': 60,
    'Cierre técnicas': '',
    'Cierre evidencia': '',
    'Cierre eva diag': '',
    'Cierre eva inst': '',
    'Cierre eva pond': 15,
    'Materiales': '',
    'Equipo': '',
    'Fuentes': '',
    'Elaboró':'',
    'Revisó': '',
    'Avaló': '',
    'Ponderación pg': 20,
    'src1':'https://peninsula360press.com/wp-content/uploads/2021/01/wp2297919-1600x1000.jpg',
    'Ejercicios': 'Con las técnicas y las herramientas que ya vimos anteriormente, ahora buscaremos resolver situaciones diferentes.',
    'Resuelve': 'Para resolver este problema primero ...',
    'Retroalimentación': 'Con la finalidad de tener retroalimentación acerca de los temas anteriormente cubiertos, realizaremos una actividad final para entregar antes de continuar con el programa.'
  }
]


@app.route("/")
def hello_pm1():
  return render_template('home.html',
                        temas=TEMAS
                        )





@app.route('/tema/<int:tema_id>')
def show_tema(tema_id):
    # Supongamos que TEMAS es tu estructura de datos (lista o dict)
    tema = TEMAS[tema_id-1]
    return render_template('classpage.html', i=tema)
  

@app.route("/api/temas")
def list_temas():
  return jsonify(TEMAS)

#if __name__ == "__main__":
#  app.run(host="0.0.0.0", port=8080, debug=True)



if __name__ == '__main__':
    http_server = WSGIServer(('0.0.0.0', 8080), app)
    http_server.serve_forever()