from flask import Flask, render_template, jsonify

app = Flask(__name__)


TEMAS = [
  {
    'id':1,
    'Plantel': 'CBTA 205',
    'Parcial' : 'Parcial 1',
    'Docente(s)': 'M.C. Héctor René Becerril Cejudo',
    'UAC': 'Pensamiento Matemático I',
    'Tema':'Introducción',
    'Temática general': 'Experimentos de la vida cotidiana',
    'Temática específica': 'A',
    'Semestre': '1°',
    'Grupos': 'A, B y C',
    'Horas docente': '60 mins',
    'Horas independiente': '60 mins',
    'Duración':'20 min',
    'pg': 'Progresión 1',
    'Conocimientos integradores': '',
    'Dimensión': '',
    'Categoría(s)':'',
    'Subcategoría(s)':'',
    'Metas de aprendizaje':'',
    'Aprendizaje de trayectoria':'',
    'Multi 1': 'Cultura Digital - Progresión 2',
    'Multi 2': 'Cultura Digital - Progresión 3',
    'Multi 3': 'Cultura Digital - Progresión 5',
    'Evidencia M1': '',
    'Evidencia M2': '',
    'Evidencia M3': '',
    'Inter 1': 'Lengua y Comunicación - Progresión 1 - Semana 2',
    'Inter 2': 'Lengua y Comunicación - Progresión 4 - Semana 3',
    'Inter 3': 'Lengua y Comunicación - Progresión 5 - Semana 4',
    'Evidencia I1': '',
    'Evidencia I2': '',
    'Evidencia I3': '',
    'Apertura': '',
    'Apertura tiempo': '',
    'Apertura técnicas': '',
    'Apertura evidencia': '',
    'Apertura eva diag': '',
    'Apertura eva inst': '',
    'Apertura eva pond': '',
    'Desarrollo': '',
    'Desarrollo tiempo': '',
    'Desarrollo técnicas': '',
    'Desarrollo evidencia': '',
    'Desarrollo eva diag': '',
    'Desarrollo eva inst': '',
    'Desarrollo eva pond': '',
    'Cierre': '',
    'Cierre tiempo': '',
    'Cierre técnicas': '',
    'Cierre evidencia': '',
    'Cierre eva diag': '',
    'Cierre eva inst': '',
    'Cierre eva pond': '',
    'Materiales': '',
    'Equipo': '',
    'Fuentes': '',
    'Elaboró':'',
    'Revisó': '',
    'Avaló': '',
    'Evaluación': ' ',
    'Contenido': 'Hola, bienvenido a la clase de Pensamiento Matemático I. En esta clase aprenderemos a resolver problemas de manera intuitiva con base en el razonamiento lógico.',
    'Apertura': 'Para comenzar la clase, vamos a resolver un problema rescatando conocimientos previos.',
    'Caso': 'En un grupo de 10 personas, 3 personas son mujeres y 7 son hombres, ¿cuántas personas hay en total y cuántas son mujeres?',
    'src1':'https://matematicas-1.onrender.com/static/gente.jpg',
    'Desarrollo': 'Con las técnicas y las herramientas que ya vimos anteriormente, ahora buscaremos resolver situaciones diferentes.',
    'Resuelve': 'Para resolver este problema primero contamos el total de personas y luego identificamos en la lectura cuántas son mujeres?',
    'Cierre': 'Con la finalidad de tener retroalimentación acerca de los temas anteriormente cubiertos, realizaremos una actividad final antes de continuar con el programa.'
  },
  
  {
    'id':2,
    'Plantel': 'CBTA 205',
    'Parcial' : 'Parcial 1',
    'Docente(s)': 'M.C. Héctor René Becerril Cejudo',
    'UAC': 'Pensamiento Matemático I',
    'Tema':'Conteos',
    'Temática general': 'Técnicas de conteo',
    'Temática específica': 'B',
    'Semestre': '1°',
    'Grupos': 'A, B y C',
    'Horas docente': '60 mins',
    'Horas independiente': '60 mins',
    'Duración':'30 min',
    'pg': 'Progresión 2',
    'Conocimientos integradores': '',
    'Dimensión': '',
    'Categoría(s)':'',
    'Subcategoría(s)':'',
    'Metas de aprendizaje':'',
    'Aprendizaje de trayectoria':'',
    'Multi 1': 'Cultura Digital - Progresión 2',
    'Multi 2': 'Cultura Digital - Progresión 3',
    'Multi 3': 'Cultura Digital - Progresión 5',
    'Evidencia M1': '',
    'Evidencia M2': '',
    'Evidencia M3': '',
    'Inter 1': 'Lengua y Comunicación - Progresión 1 - Semana 2',
    'Inter 2': 'Lengua y Comunicación - Progresión 4 - Semana 3',
    'Inter 3': 'Lengua y Comunicación - Progresión 5 - Semana 4',
    'Evidencia I1': '',
    'Evidencia I2': '',
    'Evidencia I3': '',
    'Apertura': '',
    'Apertura tiempo': '',
    'Apertura técnicas': '',
    'Apertura evidencia': '',
    'Apertura eva diag': '',
    'Apertura eva inst': '',
    'Apertura eva pond': '',
    'Desarrollo': '',
    'Desarrollo tiempo': '',
    'Desarrollo técnicas': '',
    'Desarrollo evidencia': '',
    'Desarrollo eva diag': '',
    'Desarrollo eva inst': '',
    'Desarrollo eva pond': '',
    'Cierre': '',
    'Cierre tiempo': '',
    'Cierre técnicas': '',
    'Cierre evidencia': '',
    'Cierre eva diag': '',
    'Cierre eva inst': '',
    'Cierre eva pond': '',
    'Materiales': '',
    'Equipo': '',
    'Fuentes': '',
    'Elaboró':'',
    'Revisó': '',
    'Avaló': '',
    'Evaluación': '20%',
    'Contenido': 'En esta clase aprenderemos algunas técnicas útiles para contar objetos.',
    'Apertura': 'Para comenzar la clase, vamos a resolver un problema rescatando conocimientos previos.',
    'Caso': 'En un aparador de una tienda de teléfonos celulares hay 3 marcas diferentes. De la primera marca hay 5 modelos, de la segunda marca hay 4 modelos y de la tercera marca hay 6 modelos. ¿Cuántos modelos de teléfonos celulares hay en total?',
'src1':'https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExOHVoZjZtczZwbXJqbms4YmNvZ2lidjk2cDBjcmxqZzloNmR1bnc0eSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/JIX9t2j0ZTN9S/giphy.gif',
    'Desarrollo': 'Con las técnicas y las herramientas que ya vimos anteriormente, ahora buscaremos resolver situaciones diferentes.',
    'Resuelve': 'Para resolver este problema primero contamos los modelos de cada marca y luego sumamos para obtener el total',
    'Cierre': 'Con la finalidad de tener retroalimentación acerca de los temas anteriormente cubiertos, realizaremos una actividad final antes de continuar con el programa.'
  },
  
  {
    'id':3,
    'Plantel': 'CBTA 205',
    'Parcial' : 'Parcial 2',
    'Docente(s)': 'M.C. Héctor René Becerril Cejudo',
    'UAC': 'Pensamiento Matemático I',
    'Tema':'Tablas',
    'Temática general': 'Ordenar y presentar información',
    'Temática específica': 'C',
    'Semestre': '1°',
    'Grupos': 'A, B y C',
    'Horas docente': '60 mins',
    'Horas independiente': '60 mins',
    'Duración':'50 min',
    'pg': 'Progresión 3',
    'Conocimientos integradores': '',
    'Dimensión': '',
    'Categoría(s)':'',
    'Subcategoría(s)':'',
    'Metas de aprendizaje':'',
    'Aprendizaje de trayectoria':'',
    'Multi 1': 'Cultura Digital - Progresión 2',
    'Multi 2': 'Cultura Digital - Progresión 3',
    'Multi 3': 'Cultura Digital - Progresión 5',
    'Evidencia M1': '',
    'Evidencia M2': '',
    'Evidencia M3': '',
    'Inter 1': 'Lengua y Comunicación - Progresión 1 - Semana 2',
    'Inter 2': 'Lengua y Comunicación - Progresión 4 - Semana 3',
    'Inter 3': 'Lengua y Comunicación - Progresión 5 - Semana 4',
    'Evidencia I1': '',
    'Evidencia I2': '',
    'Evidencia I3': '',
    'Apertura': '',
    'Apertura tiempo': '',
    'Apertura técnicas': '',
    'Apertura evidencia': '',
    'Apertura eva diag': '',
    'Apertura eva inst': '',
    'Apertura eva pond': '',
    'Desarrollo': '',
    'Desarrollo tiempo': '',
    'Desarrollo técnicas': '',
    'Desarrollo evidencia': '',
    'Desarrollo eva diag': '',
    'Desarrollo eva inst': '',
    'Desarrollo eva pond': '',
    'Cierre': '',
    'Cierre tiempo': '',
    'Cierre técnicas': '',
    'Cierre evidencia': '',
    'Cierre eva diag': '',
    'Cierre eva inst': '',
    'Cierre eva pond': '',
    'Materiales': '',
    'Equipo': '',
    'Fuentes': '',
    'Elaboró':'',
    'Revisó': '',
    'Avaló': '',
    'Evaluación': '30%',
    'Contenido': 'Las tablas son una herramienta útil para organizar información y resolver problemas.',
    'Apertura': 'Para comenzar la clase, vamos a resolver un problema rescatando conocimientos previos.',
    'Caso': '¿Recuerdas las marcas de teléfonos celulares que contamos en la clase anterior? Ahora vamos a organizar la información en una tabla.',
    'src1':'https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExeW5xNmwzMnhxMWkwZmRwYWU4c2xydzFwYnB2ZWp6ems1NzkyZjh0cCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/BemKqR9RDK4V2/giphy.gif',
    'Desarrollo': 'Con las técnicas y las herramientas que ya vimos anteriormente, ahora buscaremos resolver situaciones diferentes.',
    'Resuelve': 'Con ayuda de tu ptofesor en clase, organiza la información de los teléfonos celulares en una tabla. Recuerda que una tabla debe tener enccabezados y su estructura consiste en filas y columnas. No olvides además incluir un título en la parte superior de la tabla. El título debe ser breve y claro y debe indicar el contenido de la tabla.',
    'Cierre': 'Con la finalidad de tener retroalimentación acerca de los temas anteriormente cubiertos, realizaremos una actividad final antes de continuar con el programa.'
  },
  {
    'id':4,
    'Plantel': 'CBTA 205',
    'Parcial' : 'Parcial 3',
    'Docente(s)': 'M.C. Héctor René Becerril Cejudo',
    'UAC': 'Pensamiento Matemático I',
    'Tema':'Proporcionalidad',
    'Temática general': 'Relaciones entre cantidades',
    'Temática específica': 'D',
    'Semestre': '1°',
    'Grupos': 'A, B y C',
    'Horas docente': '60 mins',
    'Horas independiente': '60 mins',
    'Duración':'120 min',
    'pg': 'Progresión 4',
    'Conocimientos integradores': '',
    'Dimensión': '',
    'Categoría(s)':'',
    'Subcategoría(s)':'',
    'Metas de aprendizaje':'',
    'Aprendizaje de trayectoria':'',
    'Multi 1': 'Cultura Digital - Progresión 2',
    'Multi 2': 'Cultura Digital - Progresión 3',
    'Multi 3': 'Cultura Digital - Progresión 5',
    'Evidencia M1': '',
    'Evidencia M2': '',
    'Evidencia M3': '',
    'Inter 1': 'Lengua y Comunicación - Progresión 1 - Semana 2',
    'Inter 2': 'Lengua y Comunicación - Progresión 4 - Semana 3',
    'Inter 3': 'Lengua y Comunicación - Progresión 5 - Semana 4',
    'Evidencia I1': '',
    'Evidencia I2': '',
    'Evidencia I3': '',
    'Apertura': '',
    'Apertura tiempo': '',
    'Apertura técnicas': '',
    'Apertura evidencia': '',
    'Apertura eva diag': '',
    'Apertura eva inst': '',
    'Apertura eva pond': '',
    'Desarrollo': '',
    'Desarrollo tiempo': '',
    'Desarrollo técnicas': '',
    'Desarrollo evidencia': '',
    'Desarrollo eva diag': '',
    'Desarrollo eva inst': '',
    'Desarrollo eva pond': '',
    'Cierre': '',
    'Cierre tiempo': '',
    'Cierre técnicas': '',
    'Cierre evidencia': '',
    'Cierre eva diag': '',
    'Cierre eva inst': '',
    'Cierre eva pond': '',
    'Materiales': '',
    'Equipo': '',
    'Fuentes': '',
    'Elaboró':'',
    'Revisó': '',
    'Avaló': '',
    'Evaluación': '50%',
    'Contenido': 'En esta clase aprenderemos a resolver problemas que involucran relaciones entre cantidades.',
    'Apertura': 'Para comenzar la clase, vamos a resolver un problema rescatando conocimientos previos.',
    'Caso': 'En un grupo de 10 personas, 3 personas son hombres y 7 son mujeres, ¿Cuál es la proporción de hombres y mujeres?',
    'src1':'https://peninsula360press.com/wp-content/uploads/2021/01/wp2297919-1600x1000.jpg',
    'Desarrollo': 'Con las técnicas y las herramientas que ya vimos anteriormente, ahora buscaremos resolver situaciones diferentes.',
    'Resuelve': 'Para resolver este problema primero contamos el total de personas que hay en el grupo y luego identificamos cuántas son hombres y cuántas son mujeres. Finalmente, dividimos el número de hombres entre el total de personas para obtener la proporción de hombres; hacemos el mismo procedimiento para obtener la proporción de mujeres.',
    'Cierre': 'Con la finalidad de tener retroalimentación acerca de los temas anteriormente cubiertos, realizaremos una actividad final para entregar antes de continuar con el programa.'
  },
]

@app.route("/")
def hello_pm1():
  return render_template('home.html',
                        temas=TEMAS
                        )





@app.route('/tema/<int:tema_id>')
def show_tema(tema_id):
    # Supongamos que TEMAS es tu estructura de datos (lista o dict)
    tema = TEMAS[tema_id-1]
    return render_template('classpage.html', i=tema)
  

@app.route("/api/temas")
def list_temas():
  return jsonify(TEMAS)

if __name__ == "__main__":
  app.run(host="0.0.0.0", port=8080, debug=True)