from flask import Flask, render_template, jsonify

from gevent import monkey; monkey.patch_all()
from gevent.pywsgi import WSGIServer

app = Flask(__name__)


TEMAS = [
  {
    'id':1,
    'Plantel': 'CBTA 205',
    'Parcial' : 'Parcial 1',
    'Docente(s)': 'M.C. Héctor René Becerril Cejudo',
    'UAC': 'Pensamiento Matemático I',
    'Tema':'Introducción',
    'Temática general': 'Experimentos de la vida cotidiana',
    'Temática específica': 'Presentación del curso y criterios de evaluación',
    'Semestre': '1°',
    'Grupos': 'A, B y C',
    'Horas docente': '45 mins',
    'Horas independiente': '15 mins',

    'pg': 'Progresión 1',
    'pg desc': 'iscute la importancia de la toma razonada de decisiones, tanto a nivel personal como colectivo, utilizando ejemplos reales o ficticios y de problemáticas complejas que sean significativas para valorar la recolección de datos, su organización y la aleatoriedad.<br><br>Se busca llevar al estudiantado a que aprecie el poder de la matemática y el pensamiento estadístico y probabilístico. En este punto no se espera que se resuelvan las problemáticas abordadas.',
    'Conocimientos integradores': '',
    'Dimensión': '',
    'Categoría(s)':'<b>C2</b> Procesos de intuición y razonamiento.',
    'Subcategoría(s)':'<b>S1</b> Capacidad para observar y conjeturar. ',
    'Metas de aprendizaje':'<b>M1</b> Observa y obtiene información de una situación o fenómeno para establecer estrategias o formas de visualización que ayuden a entenderlo. ',
    'Aprendizaje de trayectoria':'',
    'Multi 1': 'Cultura Digital - Progresión 2',
    'Multi 2': 'Cultura Digital - Progresión 3',
    'Multi 3': 'Cultura Digital - Progresión 5',
    'Evidencia M1': '',
    'Evidencia M2': '',
    'Evidencia M3': '',
    'Inter 1': 'Lengua y Comunicación - Progresión 1 - Semana 2',
    'Inter 2': 'Lengua y Comunicación - Progresión 4 - Semana 3',
    'Inter 3': 'Lengua y Comunicación - Progresión 5 - Semana 4',
    'Evidencia I1': '',
    'Evidencia I2': '',
    'Evidencia I3': '',
    'Apertura': 'A partir de una conversación guiada, se lanzarán un par de preguntas detonantes acerca de la importancia del manejo e interpretación de la información en la vida cotidiana y en algunos contextos de la vida moderna.<br><br>    Las preguntas detonantes son:<br> ¿Cómo saber donde conviene comprar un producto de interés? ¿Es probable que mi equipo favorito gane el próximo partido? ¿Qué tan probable es que en mi familia alguien se enferme de la piel? Se realizará la laectura de las preguntas y se compartirán respuestas en el grupo.',
    'Apertura tiempo': 'Docente 25 - Independiente: 5',
    'Apertura tiempo total': 30,
    'Apertura técnicas': 'Conversación guiada y preguntas detonantes',
    'Apertura evidencia': '',
    'Apertura eva diag': 'Participación grupal, lluvia de ideas',
    'Apertura eva inst': '',
    'Apertura eva pond': 0,
    'Desarrollo': 'A partir de los ejemplos y situaciones presentadas durante la Apertura, cada estudiante redactará ejemplos de su vida cotidiana o de situaciones que ha visto a través de los medios, y en las que es importante contar con información para poder tomar la decisión adecuada.',
    'Desarrollo tiempo': 'Docente: 60 min - Independiente: 30 min',
    'Desarrollo tiempo total': 90,
    'Desarrollo técnicas': 'Lluvia de ideas y elaboración de un resumen.',
    'Desarrollo evidencia': 'Resumen',
    'Desarrollo eva diag': '',
    'Desarrollo eva inst': 'Lista de cotejo',
    'Desarrollo eva pond': 5,
    'Cierre': 'Haciendo uso de las TICCAD cada estudiante redactará una reflexión acerca de la importancia del manejo de la información para la toma de decisiones y esta infomración la envirá al docente vía electrónica utilizando un e.mail.',
    'Cierre tiempo': 'Docente 60 - Independiente 0',
    'Cierre tiempo total': 60,
    'Cierre técnicas': 'Resumen y uso de las TICCAD',
    'Cierre evidencia': 'Correo electrónico y resumen',
    'Cierre eva diag': '',
    'Cierre eva inst': 'Lista de cotejo',
    'Cierre eva pond': 5,
    'Materiales': '',
    'Equipo': 'Computadora o dispositivo móbil',
    'Fuentes': '',
    'Elaboró':'M.C. Héctor René Becerril Cejudo',
    'Revisó': 'Ing. Ana Lucía Gallegos',
    'Avaló': 'Ing. José Luis Alcalá López',
    'Ponderación': 10,
    'Contenido': 'Se busca llevar al estudiantado a que aprecie el poder de la matemática y el pensamiento estadístico y probabilístico.',
    'Caso': 'En un grupo de 10 personas, 3 personas son mujeres y 7 son hombres, ¿cuántas personas hay en total y cuántas son mujeres?',
    'src1':'https://matematicas-1.onrender.com/static/gente.jpg',
    'Ejercicios': 'Con las técnicas y las herramientas que ya vimos anteriormente, ahora buscaremos resolver situaciones diferentes.',
    'Resuelve': 'Para resolver este problema primero contamos el total de personas y luego identificamos en la lectura cuántas son mujeres?',
    'Retroalimentación': 'Con la finalidad de tener retroalimentación acerca de los temas anteriormente cubiertos, realizaremos una actividad final antes de continuar con el programa.'
  },
  
  {
    'id':2,
    'Plantel': 'CBTA 205',
    'Parcial' : 'Parcial 1',
    'Docente(s)': 'M.C. Héctor René Becerril Cejudo',
    'UAC': 'Pensamiento Matemático I',
    'Tema':'Conteos',
    'Temática general': 'Técnicas de conteo',
    'Temática específica': 'B',
    'Semestre': '1°',
    'Grupos': 'A, B y C',
    'Horas docente': '60 mins',
    'Horas independiente': '60 mins',

    'pg': 'Progresión 2',
    'pg desc': '',
    'Conocimientos integradores': '',
    'Dimensión': '',
    'Categoría(s)':'',
    'Subcategoría(s)':'',
    'Metas de aprendizaje':'',
    'Aprendizaje de trayectoria':'',
    'Multi 1': 'Cultura Digital - Progresión 2',
    'Multi 2': 'Cultura Digital - Progresión 3',
    'Multi 3': 'Cultura Digital - Progresión 5',
    'Evidencia M1': '',
    'Evidencia M2': '',
    'Evidencia M3': '',
    'Inter 1': 'Lengua y Comunicación - Progresión 1 - Semana 2',
    'Inter 2': 'Lengua y Comunicación - Progresión 4 - Semana 3',
    'Inter 3': 'Lengua y Comunicación - Progresión 5 - Semana 4',
    'Evidencia I1': '',
    'Evidencia I2': '',
    'Evidencia I3': '',
    'Apertura': '',
    'Apertura tiempo': '',
    'Apertura tiempo total': 30,
    'Apertura técnicas': '',
    'Apertura evidencia': '',
    'Apertura eva diag': '',
    'Apertura eva inst': '',
    'Apertura eva pond': 2,
    'Desarrollo': '',
    'Desarrollo tiempo': '',
    'Desarrollo tiempo total': 0,
    'Desarrollo técnicas': '',
    'Desarrollo evidencia': '',
    'Desarrollo eva diag': '',
    'Desarrollo eva inst': '',
    'Desarrollo eva pond': 15,
    'Cierre': '',
    'Cierre tiempo': '',
    'Cierre tiempo total': 0,
    'Cierre técnicas': '',
    'Cierre evidencia': '',
    'Cierre eva diag': '',
    'Cierre eva inst': '',
    'Cierre eva pond': 5,
    'Materiales': '',
    'Equipo': '',
    'Fuentes': '',
    'Elaboró':'',
    'Revisó': '',
    'Avaló': '',

    'Contenido': 'En esta clase aprenderemos algunas técnicas útiles para contar objetos.',
    'Caso': 'En un aparador de una tienda de teléfonos celulares hay 3 marcas diferentes. De la primera marca hay 5 modelos, de la segunda marca hay 4 modelos y de la tercera marca hay 6 modelos. ¿Cuántos modelos de teléfonos celulares hay en total?',
'src1':'https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExOHVoZjZtczZwbXJqbms4YmNvZ2lidjk2cDBjcmxqZzloNmR1bnc0eSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/JIX9t2j0ZTN9S/giphy.gif',
    'Ejercicios': 'Con las técnicas y las herramientas que ya vimos anteriormente, ahora buscaremos resolver situaciones diferentes.',
    'Resuelve': 'Para resolver este problema primero contamos los modelos de cada marca y luego sumamos para obtener el total',
    'Retroalimentación': 'Con la finalidad de tener retroalimentación acerca de los temas anteriormente cubiertos, realizaremos una actividad final antes de continuar con el programa.'
  },
  
  {
    'id':3,
    'Plantel': 'CBTA 205',
    'Parcial' : 'Parcial 2',
    'Docente(s)': 'M.C. Héctor René Becerril Cejudo',
    'UAC': 'Pensamiento Matemático I',
    'Tema':'Tablas',
    'Temática general': 'Ordenar y presentar información',
    'Temática específica': 'C',
    'Semestre': '1°',
    'Grupos': 'A, B y C',
    'Horas docente': '60 mins',
    'Horas independiente': '60 mins',

    'pg': 'Progresión 3',
    'pg desc': '',
    'Conocimientos integradores': '',
    'Dimensión': '',
    'Categoría(s)':'',
    'Subcategoría(s)':'',
    'Metas de aprendizaje':'',
    'Aprendizaje de trayectoria':'',
    'Multi 1': 'Cultura Digital - Progresión 2',
    'Multi 2': 'Cultura Digital - Progresión 3',
    'Multi 3': 'Cultura Digital - Progresión 5',
    'Evidencia M1': '',
    'Evidencia M2': '',
    'Evidencia M3': '',
    'Inter 1': 'Lengua y Comunicación - Progresión 1 - Semana 2',
    'Inter 2': 'Lengua y Comunicación - Progresión 4 - Semana 3',
    'Inter 3': 'Lengua y Comunicación - Progresión 5 - Semana 4',
    'Evidencia I1': '',
    'Evidencia I2': '',
    'Evidencia I3': '',
    'Apertura': '',
    'Apertura tiempo': '',
    'Apertura tiempo total': 30,
    'Apertura técnicas': '',
    'Apertura evidencia': '',
    'Apertura eva diag': '',
    'Apertura eva inst': '',
    'Apertura eva pond': 0,
    'Desarrollo': '',
    'Desarrollo tiempo': '',
    'Desarrollo tiempo total': 60,
    'Desarrollo técnicas': '',
    'Desarrollo evidencia': '',
    'Desarrollo eva diag': '',
    'Desarrollo eva inst': '',
    'Desarrollo eva pond': 1,
    'Cierre': '',
    'Cierre tiempo': '',
    'Cierre tiempo total': 20,
    'Cierre técnicas': '',
    'Cierre evidencia': '',
    'Cierre eva diag': '',
    'Cierre eva inst': '',
    'Cierre eva pond': 5,
    'Materiales': '',
    'Equipo': '',
    'Fuentes': '',
    'Elaboró':'',
    'Revisó': '',
    'Avaló': '',

    'Contenido': 'Las tablas son una herramienta útil para organizar información y resolver problemas.',
    'Caso': '¿Recuerdas las marcas de teléfonos celulares que contamos en la clase anterior? Ahora vamos a organizar la información en una tabla.',
'src1':'https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExeW5xNmwzMnhxMWkwZmRwYWU4c2xydzFwYnB2ZWp6ems1NzkyZjh0cCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/BemKqR9RDK4V2/giphy.gif',
    'Ejercicios': 'Con las técnicas y las herramientas que ya vimos anteriormente, ahora buscaremos resolver situaciones diferentes.',
    'Resuelve': 'Con ayuda de tu ptofesor en clase, organiza la información de los teléfonos celulares en una tabla. Recuerda que una tabla debe tener enccabezados y su estructura consiste en filas y columnas. No olvides además incluir un título en la parte superior de la tabla. El título debe ser breve y claro y debe indicar el contenido de la tabla.',
    'Retroalimentación': 'Con la finalidad de tener retroalimentación acerca de los temas anteriormente cubiertos, realizaremos una actividad final antes de continuar con el programa.'
  },
  {
    'id':4,
    'Plantel': 'CBTA 205',
    'Parcial' : 'Parcial 3',
    'Docente(s)': 'M.C. Héctor René Becerril Cejudo',
    'UAC': 'Pensamiento Matemático I',
    'Tema':'Proporcionalidad',
    'Temática general': 'Relaciones entre cantidades',
    'Temática específica': 'D',
    'Semestre': '1°',
    'Grupos': 'A, B y C',
    'Horas docente': '60 mins',
    'Horas independiente': '60 mins',

    'pg': 'Progresión 4',
    'pg desc': '',
    'Conocimientos integradores': '',
    'Dimensión': '',
    'Categoría(s)':'',
    'Subcategoría(s)':'',
    'Metas de aprendizaje':'',
    'Aprendizaje de trayectoria':'',
    'Multi 1': 'Cultura Digital - Progresión 2',
    'Multi 2': 'Cultura Digital - Progresión 3',
    'Multi 3': 'Cultura Digital - Progresión 5',
    'Evidencia M1': '',
    'Evidencia M2': '',
    'Evidencia M3': '',
    'Inter 1': 'Lengua y Comunicación - Progresión 1 - Semana 2',
    'Inter 2': 'Lengua y Comunicación - Progresión 4 - Semana 3',
    'Inter 3': 'Lengua y Comunicación - Progresión 5 - Semana 4',
    'Evidencia I1': '',
    'Evidencia I2': '',
    'Evidencia I3': '',
    'Apertura': '',
    'Apertura tiempo': '',
    'Apertura tiempo total': 30,
    'Apertura técnicas': '',
    'Apertura evidencia': '',
    'Apertura eva diag': '',
    'Apertura eva inst': '',
    'Apertura eva pond': 0,
    'Desarrollo': '',
    'Desarrollo tiempo': '',
    'Desarrollo tiempo total': 120,
    'Desarrollo técnicas': '',
    'Desarrollo evidencia': '',
    'Desarrollo eva diag': '',
    'Desarrollo eva inst': '',
    'Desarrollo eva pond': 5,
    'Cierre': '',
    'Cierre tiempo': '',
    'Cierre tiempo total': 60,
    'Cierre técnicas': '',
    'Cierre evidencia': '',
    'Cierre eva diag': '',
    'Cierre eva inst': '',
    'Cierre eva pond': 5,
    'Materiales': '',
    'Equipo': '',
    'Fuentes': '',
    'Elaboró':'',
    'Revisó': '',
    'Avaló': '',
 
    'Contenido': 'En esta clase aprenderemos a resolver problemas que involucran relaciones entre cantidades.',
    'Caso': 'En un grupo de 10 personas, 3 personas son hombres y 7 son mujeres, ¿Cuál es la proporción de hombres y mujeres?',
    'src1':'https://peninsula360press.com/wp-content/uploads/2021/01/wp2297919-1600x1000.jpg',
    'Ejercicios': 'Con las técnicas y las herramientas que ya vimos anteriormente, ahora buscaremos resolver situaciones diferentes.',
    'Resuelve': 'Para resolver este problema primero contamos el total de personas que hay en el grupo y luego identificamos cuántas son hombres y cuántas son mujeres. Finalmente, dividimos el número de hombres entre el total de personas para obtener la proporción de hombres; hacemos el mismo procedimiento para obtener la proporción de mujeres.',
    'Retroalimentación': 'Con la finalidad de tener retroalimentación acerca de los temas anteriormente cubiertos, realizaremos una actividad final para entregar antes de continuar con el programa.'
  },
]



@app.route("/")
def hello_pm1():
  return render_template('home.html',
                        temas=TEMAS
                        )





@app.route('/tema/<int:tema_id>')
def show_tema(tema_id):
    # Supongamos que TEMAS es tu estructura de datos (lista o dict)
    tema = TEMAS[tema_id-1]
    return render_template('classpage.html', i=tema)
  

@app.route("/api/temas")
def list_temas():
  return jsonify(TEMAS)

#if __name__ == "__main__":
#  app.run(host="0.0.0.0", port=8080, debug=True)



if __name__ == '__main__':
    http_server = WSGIServer(('0.0.0.0', 8080), app)
    http_server.serve_forever()